name: CD - Deploy to Azure Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

# These permissions are required for the OIDC flow to work
permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          # Upload the entire directory, including node_modules
          path: .

  deploy:
    name: Deploy to Azure
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'Production' # Optional: You can configure a GitHub Environment for protection rules
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 'Azure Login using OIDC'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Function App'
        uses: azure/functions-action@v1
        with:
          app-name: 'mzh-heavens-above-scraper'
          # Deploy the artifact content from the current directory
          package: '.'